name       : haskell-haddock-library
version    : 1.4.3
release    : 1
source     :
    - https://hackage.haskell.org/package/haddock-library-1.4.3/haddock-library-1.4.3.tar.gz : f764763f8004715431a184a981493781b8380e13fd89ca0075ac426edc5d445b
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haddock is a documentation-generation tool for Haskell libraries. These modules expose some functionality of it without pulling in the GHC dependency.
description: |
    Haddock is a documentation-generation tool for Haskell libraries. These modules expose some functionality of it without pulling in the GHC dependency.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
