name       : haskell-haddock-library
version    : 1.7.0
release    : 3
source     :
    - https://hackage.haskell.org/package/haddock-library-1.7.0/haddock-library-1.7.0.tar.gz : e7c2794a7eb352824f098cafa07bc0506f2c3633808bfbf4c64aef0ba664d011
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haddock is a documentation-generation tool for Haskell libraries. These modules expose some functionality of it without pulling in the GHC dependency.
description: |
    Haddock is a documentation-generation tool for Haskell libraries. These modules expose some functionality of it without pulling in the GHC dependency.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
